ignores:
  - '@babel/core'
  - "@size-limit/preset-small-lib"
  - "@types/jest"
  - "@typescript-eslint/parser"
  - babel-jest
  - clibuilder-plugin-dummy
  - jest-*
  - standard-log-color
  - ts-jest
  - tslib
  - bad-plugin
  - bad-plugin-no-index
  - cjs-plugin
  - esm-plugin
  - plugin-two
