ignores:
  - "@repobuddy/jest"
  - "@types/jest"
  - "@typescript-eslint/parser"
  - clibuilder-plugin-dummy
  - jest-*
  - standard-log-color
  - ts-jest
  - tslib
  - bad-plugin
  - bad-plugin-no-index
  - cjs-plugin
  - esm-plugin
  - plugin-two
