language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
branches:
  only:
    - master
    - /^greenkeeper.*$/

script:
  - npm run verify

after_success:
  - ./scripts/run-on-node-version.sh 9 "npm install --no-save coveralls && npm run coveralls"
  - ./scripts/run-on-node-version.sh 9 "npm install --no-save codecov && npm run codecov"
